Update README.md
paseo-network/support pull request #8
Opened 2024-02-08 22:30 UTC by educlerici-zondax

Update README.md

2024-02-12 11:10 UTC, al3mart approved these changes
Looks good. Thanks!!!

2024-02-14 19:49 UTC, educlerici-zondax commented
@hbulgarini can you review this please?

2024-02-21 10:15 UTC, hbulgarini requested changes

2024-02-21 10:15 UTC, hbulgarini commented on README.md
> +- **documentation**: For issues related to documentation.
```suggestion
- **documentation**: For issues related to documentation.
-**core**: For support activities assigned to the Paseo Core Team.
```

2024-02-21 10:42 UTC, hbulgarini approved these changes

2024-02-21 10:42 UTC, merged